### ISSUE TITLE
db hint

### ISSUE THREAD

**Issue by vitaly-t** [kylekthompson/WodUp#14]
your use of type `QueryFile` isn't good, it is supposed to be initialized once and then reused.

See [the api](http://vitaly-t.github.io/pg-promise/QueryFile.html), plus [pg-promise-demo](https://github.com/vitaly-t/pg-promise-demo).

**Comment by kylekthompson** [comment]
@vitaly-t Thanks for the issue!

Quick question: instead of initializing everything in one file, would initializing the `QueryFile`s at the top of each model be ok (as opposed to inside of each method)?

**Comment by kylekthompson** [comment]
For an example:

```
const indexQuery = sqlFromFile(path.join(__dirname, 'sql/index.sql'));

class Athlete extends Model {
  static index() {
    return query(indexQuery, ...); 
  }
}
```

**Comment by vitaly-t** [comment]
Each module in Node.js executes only once, so it is ok ;)

**Comment by kylekthompson** [comment]
Thanks! Sorry for the stupid question haha. I'm new to Node :)
